services:
  backend:
    build:
      context: ../backend
    container_name: mobility-nav-backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend/app:/app/app
    working_dir: /app

  frontend:
    build:
      context: ../frontend
    container_name: mobility-nav-frontend
    ports:
      - "8050:8050"
    volumes:
      - ../frontend:/app
    working_dir: /app
    depends_on:
      - backend